# Generated by Django 4.1 on 2024-01-18 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.TimeField(default=datetime.datetime(2024, 1, 18, 6, 45, 49, 803059, tzinfo=datetime.timezone.utc))),
                ('state', models.CharField(choices=[('next', 'پرداخت بعدی'), ('success', 'موفق')], default='next', max_length=20)),
                ('total_months', models.IntegerField()),
                ('expiration', models.IntegerField(default=6)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=20)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institute')),
            ],
        ),
        migrations.CreateModel(
            name='MehrUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('help_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.charityhelp')),
            ],
        ),
        migrations.AddField(
            model_name='charityhelp',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.project'),
        ),
        migrations.AddField(
            model_name='charityhelp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.mehruser'),
        ),
    ]
