# Generated by Django 4.1 on 2024-01-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityhelp',
            name='date',
            field=models.DateField(default='Dey 1402'),
        ),
        migrations.AlterField(
            model_name='mehruser',
            name='help_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.charityhelp'),
        ),
    ]
