# Generated by Django 4.1 on 2024-01-30 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_charityhelp_date_alter_mehruser_help_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mehruser',
            name='help_history',
        ),
        migrations.AlterField(
            model_name='charityhelp',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 30, 9, 22, 17, 460070)),
        ),
    ]
