# Generated by Django 4.2.9 on 2024-02-20 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mehruser_firstname_mehruser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='app/project_logos'),
        ),
        migrations.AlterField(
            model_name='charityhelp',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 20, 18, 46, 4, 764491)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.ImageField(upload_to='app/institute_logos'),
        ),
    ]
