# Generated by Django 4.1 on 2024-02-23 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_charityhelp_options_alter_institute_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityhelp',
            name='total_months',
        ),
        migrations.AlterField(
            model_name='charityhelp',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 23, 17, 30, 1, 352315)),
        ),
    ]
