# Generated by Django 4.1 on 2024-03-01 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_charityhelp_total_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityhelp',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 2, 0, 20, 2, 382805)),
        ),
        migrations.AlterField(
            model_name='charityhelp',
            name='state',
            field=models.CharField(choices=[('next', 'پرداخت بعدی'), ('success', 'موفق'), ('expired', 'انقضا شده')], default='next', max_length=20),
        ),
    ]
