# Generated by Django 4.1 on 2024-03-01 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_charityhelp_date_alter_charityhelp_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityhelp',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 2, 0, 29, 23, 56353)),
        ),
    ]
